version: '3.8'

services:
  rpc-tests:
    build: .
    volumes:
      - ./reports:/usr/src/app/reports
    environment:
      - RPC_URL=${RPC_URL}
      - WEBSOCKET=${WEBSOCKET}
      - SEED_PHRASE=${SEED_PHRASE}
    command: >
      sh -c "if [ \"$TEST_ENV\" = 'local' ]; then npm run test:rpc:local; else npm run test:rpc:testnet; fi"
