name: zkVerify E2E Tests

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:
  pull_request:

jobs:
  e2e-build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: e2e-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Pull Docker image for zkVerify
        run: docker pull horizenlabs/zkverify:latest

      - name: Run setup script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: ./setup.sh --fetch-latest --rebuild

      - name: Install npm dependencies
        run: npm install

      - name: Set up Docker containers
        run: |
          docker-compose down -v
          docker-compose build --no-cache
          docker-compose up -d

      - name: Wait for Ethereum contract to be deployed
        run: |
          MAX_WAIT_TIME=300
          wait_time=0
          while true; do
            if docker-compose exec -T anvil-node test -f /data/contract_data.txt; then
              CONTRACT_ADDRESS=$(docker-compose exec -T anvil-node sh -c "sed -n '1p' /data/contract_data.txt | cut -d ' ' -f 3")
              if [ ! -z "$CONTRACT_ADDRESS" ]; then
                echo "Contract data is ready."
                echo "NH_CONTRACT=$CONTRACT_ADDRESS" >> $GITHUB_ENV
                break
              fi
            fi
            if [ "$wait_time" -ge "$MAX_WAIT_TIME" ]; then
              echo "Timeout reached: contract data file is not ready."
              exit 1
            fi
            echo "Waiting for contract data file to be ready..."
            sleep 2
            wait_time=$((wait_time + 5))
          done

      - name: Run E2E tests
        run: |
          WEBSOCKET=ws://127.0.0.1:9944 npm run test
        env:
          NH_CONTRACT: ${{ env.NH_CONTRACT }}
