name: zkVerify E2E Tests

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:
  pull_request:

jobs:
  e2e-build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: e2e-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run setup script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: ./setup.sh --fetch-latest --rebuild

      - name: Install npm dependencies
        run: npm install

      - name: Set up Docker containers
        run: |
          docker-compose down -v
          docker-compose build --no-cache
          docker-compose up -d

      - name: Wait for Attestation Bot to be ready
        run: |
          MAX_WAIT_TIME=300
          wait_time=0
          while true; do
            CONTRACT_ADDRESS=$(docker-compose exec attestation-bot sh -c "echo \$NH_ATTEST_BOT_NH_CONTRACT_ADDRESS")
            PRIVATE_KEY=$(docker-compose exec attestation-bot sh -c "echo \$NH_ATTEST_BOT_OPERATOR_SECRET_KEY")
            if [ ! -z "$CONTRACT_ADDRESS" ] && [ ! -z "$PRIVATE_KEY" ]; then
              echo "Attestation bot is ready."
              echo "NH_CONTRACT=$CONTRACT_ADDRESS" >> $GITHUB_ENV
              echo "PRIVATE_KEY=$PRIVATE_KEY" >> $GITHUB_ENV
              break
            fi
            if [ "$wait_time" -ge "$MAX_WAIT_TIME" ]; then
              echo "Timeout reached: Attestation bot is not ready."
              exit 1
            fi
            echo "Waiting for Attestation bot to be ready..."
            sleep 5
            wait_time=$((wait_time + 5))
          done

      - name: Run E2E tests
        run: |
          WEBSOCKET=ws://127.0.0.1:9944 PRIVATE_KEY=${{ secrets.PRIVATE_KEY }} npm run test
