name: zkVerify E2E Tests

on:
  workflow_dispatch:
    inputs:
      zkverify_docker_tag:
        description: "Docker image tag for zkverify"
        type: string
      zkverify_version:
        description: "Commit hash or tag for zkVerify repository"
        type: string
      attestation_bot_branch:
        description: "Branch for attestation bot"
        required: false
        type: string
        default: "main"
      zkv_contracts_branch:
        description: "Branch for zkv attestation contracts"
        required: false
        type: string
        default: "main"
      artifact_name:
        type: string

  workflow_call:
    inputs:
      zkverify_docker_tag:
        description: "Docker image tag for zkverify"
        type: string
      zkverify_version:
        description: "Commit hash or tag for zkVerify repository"
        type: string
      attestation_bot_branch:
        description: "Branch for attestation bot"
        required: false
        type: string
        default: "main"
      zkv_contracts_branch:
        description: "Branch for zkv attestation contracts"
        required: false
        type: string
        default: "main"
      artifact_name:
        type: string
    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_TOKEN:
        required: true
      GH_TOKEN:
        required: true
      QA_SLACK_WEBHOOK_URL:
        required: true
env:
  NODE_VERSION: "20"

jobs:
  e2e-build-and-test-copy:
    runs-on: ubuntu-latest

    outputs:
      test_status: ${{ steps.run-e2e-tests.outputs.test_status }}

    steps:
      - uses: actions/checkout@v4
        with:
          repository: HorizenLabs/zkVerify-qa
          ref: yuriko/WEB3-1184
          clean: true
          fetch-depth: 1
          token: ${{ secrets.GH_TOKEN }}

      - name: Download Docker image artifact
        if: ${{ inputs.artifact_name != '' && github.event.inputs.artifact_name != '' }}
        run: echo "Download Docker image artifact"
      
      - name: Run E2E tests
        id: run-e2e-tests
        uses: ./.github/actions/e2e-test
        with:
          zkverify_docker_tag: ${{ inputs.zkverify_docker_tag || github.event.inputs.docker_tag }}
          zkverify_version: ${{ inputs.zkverify_version || github.event.inputs.zkverify_version }}
          attestation_bot_branch: ${{ inputs.attestation_bot_branch || github.event.inputs.attestation_bot_branch }}
          zkv_contracts_branch: ${{ inputs.zkv_contracts_branch || github.event.inputs.zkv_contracts_branch }}
          artifact_name: ${{ inputs.artifact_name || github.event.artifact_name }}
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          QA_SLACK_WEBHOOK_URL: ${{ secrets.QA_SLACK_WEBHOOK_URL }}
       
      - name: Print test pass
        needs: run-e2e-tests
        if: ${{ needs.run-e2e-tests.output.test_status == 'success' }}
        run: echo "Tests all passed"

      - name: Prnt test failed
        if: ${{ needs.run-e2e-tests.output.test_status != 'success' }}
        run: echo "Tests did not pass"
